import fs from 'node:fs';
import path from 'node:path';
import { T, R, FONT, DARK, DIMENSIONS } from './design-tokens';
import { FLOWS, POLICY, OPPORTUNITIES } from './flows';
import type { Email } from './content';
export const esc = (s:unknown) => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function page(title:string,body:string){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} · Puratek</title><style>*{box-sizing:border-box}body{margin:0;background:${T.page};color:${T.navy};font:16px/1.65 Arial,Helvetica,sans-serif}main{max-width:1200px;margin:auto;padding:40px 24px}header{background:${T.navy};color:white;border-top:4px solid ${T.orange};border-radius:16px;padding:32px;margin-bottom:24px}h1{font-size:36px;line-height:1.15;margin:12px 0}h2{font-size:24px}h3{font-size:18px}p{margin:8px 0 16px}a{color:${T.orangeText}}header a{color:${T.orangeOnNavy}}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:20px}.card,section{background:white;border:1px solid ${T.line};border-radius:16px;padding:24px;margin:0 0 20px}.swatch{height:70px;border-radius:12px;border:1px solid ${T.line}}code{overflow-wrap:anywhere}.pill{display:inline-block;background:${T.cream};padding:4px 12px;border-radius:100px;font-size:13px;font-weight:bold}.muted{color:${T.muted}}table{border-collapse:collapse;width:100%}td,th{text-align:left;padding:12px;border-bottom:1px solid ${T.line};vertical-align:top}img{max-width:100%;height:auto}.chain{display:flex;gap:10px;flex-wrap:wrap;align-items:center}.node{padding:12px 16px;background:${T.cream};border:1px solid ${T.orange};border-radius:12px}nav{display:flex;gap:16px;flex-wrap:wrap}.button{display:inline-block;background:${T.button};color:white;text-decoration:none;border-radius:100px;padding:15px 34px;font-weight:bold}@media(max-width:600px){main{padding:20px 12px}h1{font-size:28px}section,.card{padding:18px}table{font-size:13px}td,th{padding:7px}}</style></head><body><main><header><img src="../assets/puratek-logo-light@2x.png" width="180" height="39" alt="Puratek"><h1>${esc(title)}</h1><nav><a href="../index.html">Email library</a><a href="../brand/index.html">Brand & components</a><a href="../flows/index.html">Automation map</a><a href="../figma/index.html">Figma exports</a></nav></header>${body}</main></body></html>`;}
export function writeArtifacts(out:string,emails:Email[],assets:any[],previewDate:string){
 const write=(p:string,s:string)=>fs.writeFileSync(path.join(out,p),s);
 write('brand/tokens.json',JSON.stringify({colors:T,dark:DARK,radius:R,fonts:FONT,dimensions:DIMENSIONS},null,2));
 write('brand/index.html',page('Brand & component library',`<section><span class="pill">Existing identity preserved</span><h2>Precision, documentation, service.</h2><p>600px email canvas. Navy headers, orange accents, ivory artwork and live, editable copy. Working baseline extracted from the existing templates; new artwork is conceptual.</p></section><h2>Color system</h2><div class="grid">${Object.entries(T).map(([name,hex])=>`<div class="card"><div class="swatch" style="background:${hex}"></div><h3>${name}</h3><code>${hex}</code></div>`).join('')}</div><section><h2>Shape & typography</h2><p>Email / offer: 12px · Strategy cards: 16px · Hub cards: 14px · Buttons: 100px.</p><p>Headings: Anek Telugu → Arial; body: Cabin → Arial. Email body 16/26px; headings 32/38px desktop, 26/32px mobile. Fallback fonts remain editable.</p><p>Desktop viewport 680px with 600px email; mobile 375px. Body insets 40px / 24px.</p><a class="button" href="../preview/w1.html">Primary CTA example</a><p><a href="tokens.json">Download design tokens</a></p></section><h2>Original imagery</h2><div class="grid">${assets.map(a=>`<div class="card"><img style="border-radius:12px" src="../assets/${a.file}" alt="${esc(a.alt)}"><h3>${esc(a.id)}</h3><p>${esc(a.alt)}</p><p class="muted">${a.usedIn.join(', ').toUpperCase()} · ${Math.round(a.bytes/1024)} KB</p><p>AI-generated conceptual illustration. Not a photograph of actual facilities, documents or packaging.</p></div>`).join('')}</div><section><h2>Reusable blocks</h2><p>A preheader · B logo/header · C headline · D body · E proof · F cart/offer · G CTA · H support · I locked footer.</p><p>Text, buttons, proof blocks and coupon panels remain HTML. Images do not contain copy. Short cart notes intentionally omit artwork.</p></section>`));
 write('flows/specification.json',JSON.stringify({policy:POLICY,flows:FLOWS,opportunities:OPPORTUNITIES},null,2));
 write('flows/index.html',page('Automation map',`<section><span class="pill">Specifications • not activated</span><h2>Seven flows. Twenty-three templates.</h2><p>Each send rechecks consent, suppression, order state and the one-message-per-24-hour cap. Proposed priority: cart/support → welcome → post-purchase → repeat/win-back → broadcast.</p><p>Preview date: ${previewDate}. Timing, timezone and new copy require deployment review. No live platform connection is configured.</p><a href="specification.json">Download portable flow specifications</a></section>${FLOWS.map(f=>`<section id="${f.id}"><span class="pill">Priority ${f.priority} · Specification only</span><h2>${f.name}</h2><p><strong>Trigger:</strong> ${esc(f.trigger)}</p><div class="chain">${f.templates.map(id=>`<a class="node" href="../index.html#${id}">${id.toUpperCase()}</a>`).join('<span>→</span>')}</div><p><strong>Schedule:</strong> ${esc(f.schedule.join(' · '))}</p><p><strong>Exit:</strong> ${esc(f.exits.join('; '))}</p><p><strong>Dependencies:</strong> ${esc(f.dependencies.join('; '))}</p>${f.id==='cart'?'<p>C2a and C2b are alternatives at 24 hours, not consecutive sends. High-value or quantity carts route to H1.</p>':''}</section>`).join('')}<h2>Additional opportunities</h2><div class="grid">${OPPORTUNITIES.map(o=>`<div class="card"><span class="pill">Dependency-gated</span><h3>${o.name}</h3><p>${o.dependency}</p></div>`).join('')}</div>`));
 write('figma/index.html',page('Figma export library',`<section><span class="pill">Connector-neutral HTML</span><h2>Choose a board or a clean email.</h2><p>All assets are embedded in individual imports. Text and buttons remain HTML. Light/dark and mobile styles are explicit; no scripts or iframes are needed.</p><p>The connector name is still needed for actual import verification. Font support, native components and Auto Layout depend on that connector. Sample cart data and dates are illustrative.</p></section><div class="grid">${emails.map(e=>`<div class="card"><span class="pill">${esc(e.flow)}</span><h3>${esc(e.name)}</h3><p>${e.status==='draft'?'New draft copy':'Existing copy with documented revisions'}</p><p><a href="../boards/${e.id}.html">Strategy board</a></p>${['desktop-light','desktop-dark','mobile-light','mobile-dark'].map(v=>`<p><a href="${e.id}-${v}.html">${v.replace('-',' · ')}</a></p>`).join('')}</div>`).join('')}</div>`));
}
