import type {Email,CampaignSection,Offer} from './content';
const site='https://puratekpeptides.com';
const link=(label:string,path:string,id:string)=>({label,href:`${site}${path}?utm_source=email&utm_medium=flow&utm_campaign=${id}`});
const shop=(id:string,label='EXPLORE THE CATALOG')=>link(label,'/shop/',id);
const docs=(id:string,label='VIEW THE COA')=>link(label,'/certifications/',id);
const help=(id:string,label='CONTACT OUR TEAM')=>link(label,'/contact-us/',id);
const welcome:Offer={title:'10% OFF YOUR FIRST ORDER',code:'%%COUPON_CODE%%',terms:'Use your code at checkout.'};
const checklist:[string,string][]=[['SPECIFICATIONS · Know what you’re evaluating.','Start with the fundamentals: product identity, available size, specifications, and the information provided for the material you’re reviewing.'],['DOCUMENTATION · Know what you can verify.','Look for accessible documentation that helps you evaluate the material, including applicable testing information and batch-specific COA availability.'],['TRACEABILITY · Know what connects the material to its batch.','Batch and lot information can provide an additional layer of transparency when reviewing research materials and their accompanying documentation.']];
const evidence:[string,string][]=[['INDEPENDENT TESTING','Purity and identity are independently tested.'],['BATCH-SPECIFIC COA','Documentation is connected to the relevant batch or lot.'],['PUBLIC DOCUMENTATION','The available testing information can be reviewed before you make your decision.']];
export const PRODUCTS=[
 {name:'BPC-157 10 mg',copy:'Research material with verified batch documentation.',file:'products-r6/bpc-157-email.jpg',...link('EXPLORE BPC-157','/product/bpc-157/','w1')},
 {name:'GHK-Cu',copy:'Explore the available research material and batch information.',file:'products-r6/ghk-cu-email.jpg',...link('EXPLORE GHK-Cu','/product/ghk-cu/','w1')},
 {name:'PUR-3R',copy:'Review product details and verification information for this research material.',file:'products-r6/pur-3r-email.jpg',...link('EXPLORE PUR-3R','/product/pur-3r/','w1')},
 {name:'MOTS-c',copy:'Explore the product and its available batch documentation.',file:'products-r6/mots-c-email.jpg',...link('EXPLORE MOTS-c','/product/mots-c/','w1')},
].map(({label,...p})=>({...p,cta:label}));
export const PRODUCT_FILES=PRODUCTS.map(p=>p.file);
const bodySection=(id:string,heading:string,paragraphs:string[],cta?:Email['cta'],extra:Partial<CampaignSection>={}):CampaignSection=>({id,heading,paragraphs,cta,...extra});
type Revision={headline:string;eyebrow:string;intro:string[];sections:CampaignSection[];goal:string;subject?:string;preheader?:string;};
function remaining(e:Email):Revision {
 const cart={label:'RETURN TO MY CART',href:'%%CART_LINK%%'};
 const r:Record<string,Revision>={
 w4:{headline:'The standard stays the same.',eyebrow:'YOUR FIRST ORDER',intro:['If you’re still evaluating Puratek, start with the material’s information and the documentation behind it.'],sections:[bodySection('questions','Before you decide.',[],undefined,{items:[['Where is the documentation?','Review the available COA and match it to the relevant batch.'],['Need clarification?','Ask our team about the product information or documentation before ordering.']]}),bodySection('offer','Your first-order offer.',[],shop(e.id),{offer:welcome})],goal:'Optional welcome follow-up for engaged nonbuyers, only while the offer is valid.',subject:'Still evaluating Puratek?',preheader:'Documentation, questions and your first-order offer.'},
 c1:{headline:'Your cart. Your next step.',eyebrow:'YOUR SAVED SELECTION',intro:['Your selected research materials are saved. Review the details and continue when you’re ready.'],sections:[bodySection('cart','Review your selection.',[],cart,{cart:true}),bodySection('documentation','A question before ordering?',['If you need help locating the relevant batch document, reply to this email.'])],goal:'Restore the selected cart with minimal distraction; no new recommendations.',subject:'Your Puratek cart is saved',preheader:'Review your selected materials and continue when ready.'},
 c2a:{headline:'Start with confidence in the information.',eyebrow:'YOUR FIRST PURATEK ORDER',intro:['Choosing a research supplier starts with evaluating the material and its documentation. Your saved cart is a place to continue.'],sections:[bodySection('cart','Your saved materials.',[],undefined,{cart:true}),bodySection('offer','A first-order offer.',[],cart,{offer:{title:'10% OFF YOUR FIRST ORDER',code:'%%CART_COUPON_CODE%%',terms:'Single use. Valid until %%CART_COUPON_EXPIRY%%. Cannot be combined with other codes.'}})],goal:'First-order cart branch: answer documentation hesitation and show the approved offer.',subject:'Your saved cart and first-order offer',preheader:'Review the documentation before you decide.'},
 c2b:{headline:'A familiar supplier. A fresh review.',eyebrow:'WELCOME BACK',intro:['Your selection is still saved. Review the current product information and available batch documentation before continuing.'],sections:[bodySection('cart','Pick up where you left off.',[],cart,{cart:true})],goal:'Returning-customer branch: current batch information, no automatic discount.',subject:'Pick up your Puratek selection',preheader:'Check the current details before continuing.'},
 c3:{headline:'What would help you decide?',eyebrow:'BEFORE YOU CONTINUE',intro:['Documentation should be easy to find and understand. Here are three places to start.'],sections:[bodySection('answers','The information behind the order.',[],undefined,{items:[['Product details','Review the specifications for the material and variation you selected.'],['Batch documentation','Look for the relevant batch or lot in the available COA.'],['Order questions','Ask our team about ordering, dispatch or locating documentation.']]}),bodySection('cart','Your saved selection.',[],cart,{cart:true})],goal:'Resolve the remaining information gap without introducing a stronger discount.',subject:'Questions before you complete your order?',preheader:'Product details, batch documents and a person to ask.'},
 c4:{headline:'A person can help.',eyebrow:'A NOTE FROM PURATEK',intro:['If a documentation or ordering question is holding you up, reply to this email. Tell us what you’re reviewing and what you need to clarify.'],sections:[bodySection('support','Let’s find the right information.',['Our team can help locate a batch document or explain the ordering information.'],help(e.id))],goal:'Optional final support note only; no invented cart expiry or urgency.',subject:'Can we help with your saved selection?',preheader:'A direct route to documentation and order support.'},
 b1:{headline:'A number needs context.',eyebrow:'THE PURATEK JOURNAL · DOCUMENTATION',intro:['A reported purity value is one part of an analytical document. The material, method and batch reference help you understand what that value describes.'],sections:[bodySection('reading','Read the document in context.',[],undefined,{items:[['Material','Which material is described?'],['Analytical evidence','What was measured, and which method is stated?'],['Batch reference','Which batch or lot does the report cover?']]}),bodySection('apply','Bring the document into the decision.',['Explore the available certifications and ask our team if the batch reference is unclear.'],docs(e.id))],goal:'Educational broadcast for engaged subscribers; deepen W2 rather than repeat the welcome offer.',subject:'What sits behind a purity number?',preheader:'Material, method and batch: three details worth checking.'},
 b2:{headline:'Clarity after checkout.',eyebrow:'THE PURATEK JOURNAL · ORDER SERVICE',intro:['Documentation matters before an order. Clear communication matters after it.'],sections:[bodySection('dispatch','Know where to look.',[],undefined,{items:[['Order details','Keep your confirmation as a reference for the materials you selected.'],['Dispatch information','Check our shipping policy for the current cutoff and service details.'],['Questions','Contact the team with your order reference so we can help locate the right information.']]}),bodySection('policy','Review the current shipping information.',[],link('VIEW SHIPPING POLICY','/shipping-policy/',e.id))],goal:'Explain service touchpoints without promising an unverified dispatch outcome.',subject:'What to keep handy after checkout',preheader:'Order references, shipping information and support.'},
 b3:{headline:'An offer. The same documentation standard.',eyebrow:'A PURATEK CATALOG OFFER',intro:['If you’re already evaluating a research material, review its specifications and available documentation before deciding.'],sections:[bodySection('offer','Review the offer details.',[],shop(e.id),{offer:e.offer})],goal:'Optional approved promotion; no automatic discount calendar or product recommendations.',subject:'Your Puratek catalog offer',preheader:'Review the material and the offer terms together.'},
 p1:{headline:'The next step is keeping the details together.',eyebrow:'AFTER YOUR ORDER',intro:['Thank you for choosing Puratek. Keep your order confirmation as the starting point for questions about your selection.'],sections:[bodySection('reference','One useful reference.',['When contacting our team, include your order reference and the product or document you’re asking about. Your transactional confirmation remains the source for payment and order status.'],help(e.id))],goal:'Optional marketing service orientation; avoid duplicating the transactional receipt.',subject:'Keep your Puratek order details handy',preheader:'A useful starting point for documentation questions.'},
 p2:{headline:'Connect the material to its document.',eyebrow:'BATCH DOCUMENTATION',intro:['When your order arrives, compare the batch information on the label with the available documentation.'],sections:[bodySection('match','Make the connection.',[],undefined,{items:[['Read the label','Find the product identity and batch or lot reference.'],['Locate the document','Review the available COA for the matching material and batch.'],['Resolve a mismatch','If you cannot find a matching document, ask our team before relying on it.']]}),bodySection('documents','Keep the reference together.',['Retain the matching documentation alongside your order details.'],docs(e.id))],goal:'Post-dispatch documentation continuity; do not imply delivery before a verified event.',subject:'Your material and its batch document',preheader:'What to match when the order arrives.'},
 p3:{headline:'Was the information easy to find?',eyebrow:'YOUR ORDERING EXPERIENCE',intro:['We’d like to hear about the service around your order: finding documentation, understanding updates and reaching our team.'],sections:[bodySection('feedback','Tell us what could be clearer.',['Was a document difficult to locate? Did an order update leave a question unanswered? Reply with feedback on the ordering experience.'],help(e.id,'SHARE SERVICE FEEDBACK'))],goal:'Ask for service feedback after verified delivery; no outcome testimonials.',subject:'How clear was your Puratek ordering experience?',preheader:'Tell us about documentation and communication.'},
 p4:{headline:'Still looking for a batch document?',eyebrow:'DOCUMENTATION SUPPORT',intro:['If you need help locating documentation for an earlier order, our team can help you find the relevant reference.'],sections:[bodySection('reference','Send the details we can match.',['Include your order reference, material name and batch or lot number in your reply.'],help(e.id,'ASK ABOUT DOCUMENTATION'))],goal:'Optional documentation assistance; skip contacts with an active support case.',subject:'Help finding your batch documentation',preheader:'Your order and batch references help us locate it.'},
 r1:{headline:'A new order deserves a new review.',eyebrow:'BEFORE YOUR NEXT ORDER',intro:['A material you’ve ordered before may now have a different batch. Start with the current information when evaluating another order.'],sections:[bodySection('current','Review the current reference.',['Check the selected variation, available specifications and corresponding batch document.'],docs(e.id))],goal:'Repeat-purchase education based on engagement, never assumed usage or depletion.',subject:'Check the current batch before ordering again',preheader:'Familiar material, current documentation.'},
 r2:{headline:'Explore with the details in front of you.',eyebrow:'REVISIT THE CATALOG',intro:['When a research purchasing decision comes up, use the catalog to review the available materials and their information.'],sections:[bodySection('browse','Product information comes first.',['Open the material’s page, check its available variation and review the relevant documentation before deciding.'],shop(e.id))],goal:'An engaged-purchaser catalog invitation without speculative recommendations.',subject:'Explore the current Puratek catalog',preheader:'Product details and batch documentation, together.'},
 r3:{headline:'Planning starts with current information.',eyebrow:'YOUR NEXT RESEARCH PURCHASE',intro:['Availability, variations and batch details can change between orders. Review what is currently listed for the material you’re evaluating.'],sections:[bodySection('planning','Move at your laboratory’s pace.',['There is no purchasing schedule to follow. If a document or order detail needs clarification, ask our team.'],shop(e.id))],goal:'Low-pressure planning touchpoint, conditional on recent meaningful engagement.',subject:'Planning another research purchase?',preheader:'Check current availability and batch information first.'},
 x1:{headline:'The documentation is a place to start.',eyebrow:'RECONNECT WITH PURATEK',intro:['If you’re evaluating research suppliers again, begin with the information you can inspect.'],sections:[bodySection('return','Review before deciding.',['Explore the available batch documentation or contact the team with a question. If these emails are no longer useful, the unsubscribe link is below.'],docs(e.id))],goal:'One evidence-led re-engagement invitation for an approved consented segment.',subject:'A place to start your next supplier review',preheader:'Documentation and support from Puratek.'},
 x2:{headline:'What information are you missing?',eyebrow:'YOUR QUESTIONS ARE WELCOME',intro:['A product specification, a batch reference or an ordering detail: tell us what you need to clarify.'],sections:[bodySection('conversation','Ask before you order.',['You do not need to place an order to ask a documentation or service question. Reply here or contact our team.'],help(e.id))],goal:'Re-engagement through a useful service conversation, no fabricated familiarity.',subject:'Can we help you find the information?',preheader:'Ask about documents or ordering details.'},
 x3:{headline:'We’ll leave the next step to you.',eyebrow:'YOUR EMAIL PREFERENCES',intro:['This is the final message in this series. If our documentation and catalog emails remain useful, let us know by replying.'],sections:[bodySection('preferences','Keep only what is useful.',['Otherwise, we’ll pause marketing emails after this series. You can also unsubscribe immediately using the link below.'],{label:'MANAGE EMAIL PREFERENCES',href:'%%PREFERENCES_URL%%'})],goal:'Honor a real sunset rule after nonresponse; requires suppression integration.',subject:'Would you like to keep hearing from Puratek?',preheader:'The choice is yours.'},
 h1:{headline:'Let’s review the details together.',eyebrow:'PERSONAL ORDER SUPPORT',intro:['If your saved selection needs a closer review, our team can help with documentation and ordering questions.'],sections:[bodySection('support','A useful place to begin.',['Reply with the material or batch reference you’re reviewing and the question you need answered.'],help(e.id))],goal:'Support-led branch for complex/high-value carts; replaces standard cart reminders.',subject:'Support for your Puratek selection',preheader:'A person can help with documentation and order details.'},
 };
 if(!r[e.id])throw Error('Missing campaign role '+e.id);return r[e.id];
}
export function campaign(e:Email):Email {
 let x:Email={...e,body:[],proof:undefined,offer:undefined,secondary:undefined,afterCta:undefined,support:false,strategy:{...e.strategy,included:[],leftOut:[],compliance:['Documentation and service copy; no human-use or outcome claims.','Review real labels, documentation, offer eligibility and destination pages before publication.'],addedText:['r6 campaign: team-supplied W1–W3; other roles newly authored to extend the same documentation strategy.'],score:'Not rated',lift:'Validate eligible clicks, assisted orders and support questions; monitor complaints and suppression.'}};
 if(e.id==='w1'){
  Object.assign(x,{name:'W1 · The documentation standard',subjectA:'Welcome to Puratek. The standard is documentation.',subjectB:'Start with what you can verify',preheader:'Our approach, your first-order offer and the research catalog.',eyebrow:'WELCOME TO PURATEK',headline:'The Standard Is Documentation.',heroCopy:['In research, confidence shouldn’t come from a claim alone.','It should come from knowing what you’re buying, and having the documentation to verify it.','That’s the standard we believe research materials should be held to.'],sections:[
   {id:'welcome-offer',offer:welcome,setup:'Explore the Puratek approach to research materials.',cta:link('EXPLORE PURATEK','/',e.id)},
   {id:'verification',eyebrow:'OUR VERIFICATION APPROACH',heading:'From Batch to Documentation.',paragraphs:['We make the verification process easier to understand, and easier to evaluate.'],items:[['BATCH · Know the Batch','Start with batch-specific information, so the material you’re evaluating can be connected to its documentation.'],['TESTING · Verify the Material','Independent testing provides evidence to evaluate identity and purity.'],['DOCUMENTATION · See the Evidence','Access the documentation behind the material, rather than relying on a quality claim alone.']],setup:'A research supplier should make verification part of the experience, not something you have to chase down.',cta:docs(e.id,'EXPLORE THE STANDARD'),tone:'surface'},
   {id:'catalog',eyebrow:'EXPLORE THE CATALOG',heading:'Find What Fits Your Research.',paragraphs:['With the standard established, explore the research materials available from Puratek.','Every product is supplied for laboratory research and supported by batch-specific documentation.'],products:PRODUCTS,setup:'Prefer to see the full catalog?',cta:shop(e.id,'SHOP ALL RESEARCH PEPTIDES')}
  ]});x.strategy.goal='Establish the documentation standard, introduce verification, then offer a curated catalog path.';x.strategy.timing='Immediately after recorded marketing opt-in';
 }else if(e.id==='w2'){
  Object.assign(x,{name:'W2 · Read the evidence',subjectA:'Don’t just read the claim. Read the evidence.',subjectB:'What should a COA tell you?',preheader:'Material, analytical evidence and batch: your COA checklist.',eyebrow:'READ THE EVIDENCE',headline:'Don’t Just Read the Claim. Read the Evidence.',heroCopy:['A purity number can tell you something. But when you’re evaluating a research material, the documentation behind that number matters too.','Know what to look for. Then verify it for yourself.'],heroAction:docs(e.id,'SEE WHAT TO LOOK FOR'),sections:[
   {id:'coa-checklist',heading:'What Should a COA Actually Tell You?',paragraphs:['A useful Certificate of Analysis should give you more than a number. It should help you understand what was tested and what the reported result applies to.'],items:[['WHAT WAS TESTED?','Identify the research material covered by the documentation.'],['WHAT DID THE TEST SHOW?','Review the reported analytical result and stated specification.'],['WHICH BATCH?','Check that the documentation can be connected to the relevant batch or lot.']] as [string,string][],setup:'The goal isn’t to read every line of a COA. It’s to know which information matters when you’re evaluating the material.',tone:'surface' as const},
   {id:'open-file',eyebrow:'OPEN THE FILE',heading:'Don’t Take Our Word for It.',paragraphs:['Puratek makes batch-specific Certificates of Analysis available on its product pages, giving researchers the opportunity to review the available documentation before ordering.'],items:evidence,setup:'The evidence is there to be examined, not simply claimed.',cta:docs(e.id)},
   {id:'evaluate',eyebrow:'EXPLORE WITH THE EVIDENCE IN FRONT OF YOU',heading:'Now Put the Checklist to Work.',paragraphs:['You know what to look for.','Now explore the research materials, review the available documentation, and evaluate what fits your research needs.'],items:[['EXPLORE → REVIEW → VERIFY','Choose a material. Review the available information. Make your decision with the evidence in front of you.']],cta:shop(e.id,'EXPLORE THE MATERIALS'),setup:'Your %%COUPON_CODE%% first-order offer is available whenever you’re ready to explore.',tone:'surface'}
  ]});x.strategy.goal='Teach the COA checklist, open the documentation, then invite catalog review.';x.strategy.timing='Day 2; no first order and no competing cart message';
 }else if(e.id==='w3'){
  Object.assign(x,{name:'W3 · Know what to look for',subjectA:'Before you choose a research material',subjectB:'Specifications, documentation and traceability',preheader:'Three things worth reviewing before you order.',eyebrow:'KNOW WHAT TO LOOK FOR',headline:'Before you choose a research material, know what to look for.',heroCopy:['When evaluating research materials, the product name is only the beginning.','Specifications, documentation, and traceability can give you a clearer picture of what you’re evaluating, and help you make a more informed purchasing decision.','Here’s a simple framework to keep in mind.'],sections:[
   {id:'checklist',eyebrow:'THE 3-POINT CHECKLIST',heading:'Three things worth reviewing.',items:checklist,tone:'surface'},
   {id:'explore',eyebrow:'EXPLORE PURATEK',heading:'Now that you know what to look for, start exploring.',paragraphs:['Browse the Puratek research catalog to review available materials, product specifications, and applicable documentation.'],cta:shop(e.id,'EXPLORE RESEARCH PRODUCTS')},
   {id:'welcome-offer',eyebrow:'WELCOME OFFER',heading:'Ready when you are.',paragraphs:['If you’re making your first Puratek purchase, your welcome offer is available:'],offer:welcome,setup:'Review the products, check the available information, and decide when the time is right for your research needs.',cta:shop(e.id),tone:'surface'}
  ]});x.strategy.goal='Turn education into a practical specifications/documentation/traceability evaluation.';x.strategy.timing='Day 4; no first order and no competing cart message';
 }else{
  const r=remaining(e);Object.assign(x,{name:`${e.id.toUpperCase()} · ${r.headline}`,headline:r.headline,eyebrow:r.eyebrow,heroCopy:r.intro,sections:r.sections,subjectA:r.subject||e.subjectA,subjectB:r.subject||e.subjectB,preheader:r.preheader||e.preheader});x.strategy.goal=r.goal;
 }
 if(e.id==='w4')x.heroAction=shop(e.id,'EXPLORE PURATEK');
 x.cta=x.heroAction||x.sections!.find(s=>s.cta)?.cta||shop(e.id);
 x.cart=x.sections!.some(s=>s.cart);
 x.strategy.kpi=({Welcome:'Documentation/catalog clicks and assisted first orders; offer eligibility and complaints', 'Abandoned cart':'Restored carts and completed orders; branch and coupon performance',Broadcast:'Qualified documentation/catalog clicks and assisted orders', 'Post-purchase':'Documentation access and service feedback; support resolution', 'Repeat engagement':'Qualified catalog/documentation clicks and subsequent orders', 'Win-back':'Explicit engagement/preferences and correct sunset suppression',Support:'Qualified support replies and resolved order questions'} as Record<Email['flow'],string>)[x.flow];
 x.strategy.included=x.sections!.map(s=>s.heading||s.eyebrow||s.id);
 x.strategy.leftOut=['Unverified numeric refund promises','Human-use claims, invented tests and automatic cross-sell'];
 if(e.id==='w1')x.strategy.compliance.push('Client-requested PUR-3R draft overrides the historical internal exclusion; product and destination review remains unresolved.');
 return x;
}
export function comparisonAlternative(main:Email):Email {
 return {...main,id:'w2-alt',variantOf:'w2',name:'W2 alternative · Purity and identity',subjectB:'Purity and identity ask different questions',preheader:'Understand the distinction, then inspect the available COA.',sections:main.sections!.map(s=>s.id==='coa-checklist'?{id:'comparison',eyebrow:'PURITY VS. IDENTITY',heading:'Two questions. Different evidence.',comparison:true,setup:'Purity and identity answer different questions. Read the relevant analytical evidence alongside the material and batch reference.',tone:'surface' as const}:s),strategy:{...main.strategy,timing:'Archived editorial alternative to W2; recommended sequence uses the COA checklist',goal:'Retained purity and identity comparison for reference; not an additional send.'}};
}
