<?php
if(!defined('ABSPATH')){exit;}
add_action('admin_menu',static function(){add_management_page('Puratek Flow Rules','Puratek Flow Rules','manage_options','pfi-flow-rules',static function(){
 if(!current_user_can('manage_options')){return;}
 $rules=[
 'welcome'=>['Welcome','Opted-in US account, no orders','W1 +0h; W2 +48h; W3 +96h','Any order exits; once per account'],
 'cart'=>['Abandoned cart','Known cart; total ≤ $500 AND quantity <10','C1 +1h; C2 +24h; C3 +48h. Shared cap normally moves C2/C3 to +25h/+49h.','C2A first buyer / C2B returning buyer, rechecked at send. Purchase, empty/recovered cart exits. Re-entry ≥7 days.'],
 'support'=>['High-value cart support','Total > $500 OR quantity ≥10; replaces standard cart','H1 +1h from abandonment','Same-cart transfer preserves the original timestamp. No duplicate standard cart sequence. Re-entry ≥7 days.'],
 'post-purchase'=>['Post-purchase','Verified paid WooCommerce order','P1 payment +2h; P2 dispatch +1d; P3 delivery +7d; P4 delivery +21d','Missing events wait, never guessed. Refund/dispute/support holds. Newer order exits. Re-entry ≥1 day.'],
 'repeat'=>['Repeat engagement','Purchaser; meaningful engagement within 90 days','Last order +30d / +60d / +90d','New order or inactivity exits; support issue holds. Re-entry ≥90 days.'],
 'winback'=>['Win-back','Approved inactive purchaser segment','Last meaningful engagement +90d; actual X1 send +7d / +14d','New engagement/order exits; final nonresponse sunsets these coordinated marketing flows. Re-entry ≥365 days.'],
 'broadcast'=>['Broadcast options','Approved campaign and engaged audience; select B1 OR B2 OR B3','At approved local campaign event; ≥7 days between enrollments','Active eligible Welcome/cart holds; B3 needs approved valid 10% offer. One option per event.'],
 ];
 echo '<div class="wrap"><h1>Puratek Flow Rules</h1><p><strong>Seven primary flows · 21 templates · Import stays inactive</strong></p><div class="notice notice-warning inline"><p>Local verification profile only. Production execution is locked. Provider events, real customer consent, links, email delivery and campaign approvals need staging validation.</p></div>';
 echo '<p><a class="button button-primary" href="'.esc_url(admin_url('tools.php?page=puratek-flow-importer')).'">Open ZIP importer</a></p><h2>Shared send rules</h2><p>Consent + US country + known source + no suppression, rechecked before every send. One coordinated marketing email per rolling 24 hours. Priority: Cart/Support → Welcome → Post-purchase → Repeat/Win-back → Broadcast. Equal priority: earlier enrollment, then stable flow/run ID. Queue expires 24 hours after its due time. Relative timers use UTC elapsed time. External broadcasts and unrelated plugins are not included in this ledger.</p>';
 foreach($rules as$flow=>$rule){echo '<details style="background:#fff;border:1px solid #c3c4c7;padding:16px;margin:12px 0" open><summary style="font-size:18px;cursor:pointer"><strong>'.esc_html($rule[0]).'</strong></summary><p><strong>Entry:</strong> '.esc_html($rule[1]).'</p><p><strong>Timing:</strong> '.esc_html($rule[2]).'</p><p><strong>Routing / exit:</strong> '.esc_html($rule[3]).'</p><p><strong>Native steps:</strong> '.esc_html(implode(' → ',PFI_Lifecycle_Policy::STEPS[$flow])).'</p></details>';}
 echo '<h2>Event connections</h2><p>Account registration and WooCommerce payment-complete hooks are connected for marked synthetic local accounts. Cart abandonment/restore, dispatch, delivery, meaningful engagement, support/dispute and editorial approval enter through the explicit local PHP adapter. They are not connected to production providers. Optional W4/C4, W2 alternative and dependency-gated opportunities are not automatically activated.</p><p>Local test fields: <code>_pfi_marketing_consent</code>, <code>_pfi_country</code>, <code>_pfi_test_fixture</code>. See the supplied handoff for the exact event contract.</p></div>';
});});
